# Generated by Django 6.0.1 on 2026-03-13 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('value_days', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'academic_rules',
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('total_credits_to_graduate', models.IntegerField(default=0)),
                ('total_semester', models.IntegerField(default=0)),
                ('semester_week', models.IntegerField(default=12)),
                ('level', models.CharField(choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=20)),
                ('year_taken', models.IntegerField(default=1)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('internship', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Lab', 'Lab'), ('Classroom', 'Classroom'), ('Auditorium', 'Auditorium'), ('Office', 'Office'), ('Cafeteria', 'Cafeteria'), ('Library', 'Library'), ('Study Room', 'Library Study Room')], max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('building', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('coordinate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_bookable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text="e.g., 'A' or 'P1'", max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('node_type', models.CharField(choices=[('terminal', 'Terminal (Visible)'), ('pathway', 'Pathway (Invisible)')], default='terminal', max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_id', models.CharField(max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='academic_term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_code', models.CharField(max_length=25)),
                ('current_semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
            ],
            options={
                'db_table': 'academic_term',
            },
        ),
        migrations.CreateModel(
            name='course_enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_status', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollment', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.academic_term')),
            ],
            options={
                'db_table': 'course_enrollment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.departments'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.facilities')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GEN', 'General'), ('ANN', 'Announcements'), ('ATT', 'Attendance'), ('MAP', 'Campus Navigation'), ('BOK', 'Facility Booking')], default='GEN', max_length=3)),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('is_visitor_visible', models.BooleanField(default=False)),
                ('is_ad_visible', models.BooleanField(default=False)),
                ('is_lc_visible', models.BooleanField(default=False)),
                ('is_tp_visible', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('n_likes', models.PositiveIntegerField(default=0)),
                ('n_dislikes', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_faqs', to='campus.admin_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='lecturer_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lc_id', models.CharField(max_length=12, unique=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('max_hours_per_week', models.IntegerField(default=20)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturer_profiles',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='campus.lecturer_profiles'),
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='campus.mapnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='campus.mapnode')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.facilities')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='student_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_id', models.CharField(max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], default='Lecture', max_length=20)),
                ('parent_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_components', to='campus.subject')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='lecturer_subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'lecturer_subjects',
            },
        ),
        migrations.CreateModel(
            name='course_subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'course_subject',
            },
        ),
        migrations.CreateModel(
            name='class_session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('rearranged', 'Rearranged')], default='scheduled', max_length=20)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.academic_term')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'class_session',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('ANN', 'Announcements'), ('ATT', 'Attendance'), ('MAP', 'Campus Navigation'), ('BOK', 'Facility Booking')], default='GEN', max_length=3)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_handled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campus.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='timetable_preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preferences', to='campus.academic_term')),
            ],
            options={
                'db_table': 'timetable_preference',
            },
        ),
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late')], max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='campus.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FAQReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='campus.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faq', 'user')},
            },
        ),
        migrations.CreateModel(
            name='skipped_date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Public Holiday', max_length=255)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_dates', to='campus.academic_term')),
            ],
            options={
                'db_table': 'skipped_date',
                'unique_together': {('term', 'date')},
            },
        ),
        migrations.CreateModel(
            name='lecturer_assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='campus.academic_term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'lecturer_assignment',
                'unique_together': {('term', 'subject')},
            },
        ),
    ]
