# Generated by Django 6.0.2 on 2026-02-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('value_days', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'academic_rules',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('total_credits_to_graduate', models.IntegerField(default=0)),
                ('total_semester', models.IntegerField(default=0)),
                ('semester_week', models.IntegerField(default=12)),
                ('level', models.CharField(choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=20)),
                ('year_taken', models.IntegerField(default=1)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('internship', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Lab', 'Lab'), ('Classroom', 'Classroom'), ('Auditorium', 'Auditorium'), ('Office', 'Office'), ('Cafeteria', 'Cafeteria'), ('Library', 'Library'), ('Study Room', 'Library Study Room')], max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('building', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('coordinate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_bookable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='academic_term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_code', models.CharField(max_length=25)),
                ('current_semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
            ],
            options={
                'db_table': 'academic_term',
            },
        ),
        migrations.CreateModel(
            name='course_enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_status', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.academic_term')),
            ],
            options={
                'db_table': 'course_enrollment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.departments'),
        ),
        migrations.CreateModel(
            name='lecturer_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturer_profiles',
            },
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.facilities')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='lecturer_subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'lecturer_subjects',
            },
        ),
        migrations.CreateModel(
            name='course_subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'course_subject',
            },
        ),
        migrations.CreateModel(
            name='class_session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
            ],
            options={
                'db_table': 'class_session',
            },
        ),
    ]
