# Generated by Django 6.0.1 on 2026-03-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_session',
            name='subject',
        ),
        migrations.AddField(
            model_name='class_session',
            name='subject_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subjectcomponent'),
            preserve_default=False,
        ),
    ]
