# Generated by Django 6.0.1 on 2026-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_visitor_visible',
            field=models.BooleanField(default=False),
        ),
    ]
