# Generated by Django 6.0.1 on 2026-03-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_remove_class_session_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_preference',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable_preference',
            name='subject_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subjectcomponent'),
            preserve_default=False,
        ),
    ]
