# Generated by Django 6.0.1 on 2026-03-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemark',
            name='marked_at',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='otp',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='campus.class_session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancemark',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late')], default='ABSENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancemark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
