# Generated by Django 6.0.1 on 2026-02-26 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_mapnode_mapedge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer_profiles',
            name='lc_id',
            field=models.CharField(default='TEMP', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='admin_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_id', models.CharField(max_length=12, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='student_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_id', models.CharField(max_length=12, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
    ]
