# Generated by Django 6.0.1 on 2026-03-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_attendancemark_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemark',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_session', to='campus.attendancesession')),
            ],
        ),
    ]
