# Generated by Django 6.0.1 on 2026-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_attendancesession_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_term',
            name='intake_code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
