# Generated by Django 6.0.1 on 2026-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_cannedresponse_booking_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('ANN', 'Announcements'), ('ATT', 'Attendance'), ('MAP', 'Campus Navigation'), ('BOK', 'Facility Booking')], default='GEN', max_length=3),
        ),
    ]
