# Generated by Django 6.0.1 on 2026-03-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_alter_supportticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('', 'Please Select a Category'), ('GEN', 'General'), ('ANN', 'Announcements'), ('ATT', 'Attendance'), ('MAP', 'Campus Navigation'), ('BOK', 'Facility Booking')], default='GEN', max_length=3),
        ),
    ]
