# Generated by Django 6.0.1 on 2026-03-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_attendance_models'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GEN', 'General'), ('ANN', 'Announcements'), ('ATT', 'Attendance'), ('MAP', 'Campus Navigation'), ('BOK', 'Facility Booking')], default='GEN', max_length=3)),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('is_ad_visible', models.BooleanField(default=False)),
                ('is_lc_visible', models.BooleanField(default=False)),
                ('is_tp_visible', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('n_likes', models.PositiveIntegerField(default=0)),
                ('n_dislikes', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_author', to='campus.admin_profiles')),
            ],
        ),
    ]
