# Generated by Django 6.0.1 on 2026-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_alter_academic_term_intake_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_session',
            name='semestersemester',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
