# Generated by Django 6.0.1 on 2026-03-13 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class_session',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class_session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('rearranged', 'Rearranged')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='class_session',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.academic_term'),
        ),
        migrations.AddField(
            model_name='lecturer_profiles',
            name='max_hours_per_week',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], default='Lecture', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_components', to='campus.subject'),
        ),
        migrations.CreateModel(
            name='timetable_preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preferences', to='campus.academic_term')),
            ],
            options={
                'db_table': 'timetable_preference',
            },
        ),
        migrations.CreateModel(
            name='lecturer_assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='campus.academic_term')),
            ],
            options={
                'db_table': 'lecturer_assignment',
                'unique_together': {('term', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='skipped_date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Public Holiday', max_length=255)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_dates', to='campus.academic_term')),
            ],
            options={
                'db_table': 'skipped_date',
                'unique_together': {('term', 'date')},
            },
        ),
    ]
