# Generated by Django 6.0.1 on 2026-03-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_class_session_semestersemester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_session',
            old_name='semestersemester',
            new_name='semester',
        ),
    ]
