# Generated by Django 6.0.1 on 2026-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_ticketactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='action',
            field=models.CharField(choices=[('status_change', 'Updated Status'), ('escalation', 'Escalated Ticket '), ('closure_request', 'Closure Requested'), ('rejected_closure', 'Rejected Closure Requested')], max_length=20),
        ),
    ]
