# Generated by Django 6.0.1 on 2026-03-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_alter_ticketactivity_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CannedResponse',
        ),
    ]
