# Generated by Django 6.0.1 on 2026-03-17 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_delete_cannedresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='is_bookable',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credit_hour',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parent_subject',
        ),
        migrations.CreateModel(
            name='AnnouncementTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_for_students', models.BooleanField(default=False)),
                ('is_for_lecturer', models.BooleanField(default=False)),
                ('is_for_admins', models.BooleanField(default=False)),
                ('academic_term', models.CharField(blank=True, max_length=50, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campus.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_per_class', models.IntegerField(default=0)),
                ('total_required_hours', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab'), ('Practical', 'Practical'), ('Fieldwork', 'Fieldwork')], default='Lecture', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='campus.subject')),
            ],
        ),
    ]
