# Generated by Django 6.0.1 on 2026-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_announcement_remove_facilities_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcomponent',
            name='hours_per_class',
            field=models.IntegerField(default=2),
        ),
    ]
