# Generated by Django 6.0.1 on 2026-03-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_alter_subjectcomponent_hours_per_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='building',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='coordinate',
        ),
    ]
