# Generated by Django 6.0.1 on 2026-03-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_remove_facilities_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('BANNER', 'Rolling Banner'), ('NORMAL', 'Normal News')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ann', to='campus.admin_profiles'),
        ),
        migrations.AlterField(
            model_name='announcementtarget',
            name='is_for_admins',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcementtarget',
            name='is_for_lecturer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcementtarget',
            name='is_for_students',
            field=models.BooleanField(default=True),
        ),
    ]
