# Generated by Django 6.0.1 on 2026-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_announcement_announcement_type_announcement_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementtarget',
            name='is_visitor_visible',
            field=models.BooleanField(default=False),
        ),
    ]
