# Generated by Django 6.0.1 on 2026-03-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_alter_announcement_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='campus_announcement',
        ),
        migrations.AlterModelTable(
            name='announcementtarget',
            table='campus_announcementTarget',
        ),
        migrations.AlterModelTable(
            name='attachments',
            table='campus_attachments',
        ),
        migrations.AlterModelTable(
            name='attendancemark',
            table='campus_attendanceMark',
        ),
        migrations.AlterModelTable(
            name='attendancesession',
            table='campus_AttendanceSession',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='campus_faq',
        ),
        migrations.AlterModelTable(
            name='faqreaction',
            table='campus_faqreaction',
        ),
        migrations.AlterModelTable(
            name='mapedge',
            table='campus_mapedge',
        ),
        migrations.AlterModelTable(
            name='mapnode',
            table='campus_mapnode',
        ),
        migrations.AlterModelTable(
            name='subjectcomponent',
            table='campus_subjectcomponent',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='campus_supportticket',
        ),
        migrations.AlterModelTable(
            name='ticketactivity',
            table='campus_ticketactivity',
        ),
        migrations.AlterModelTable(
            name='ticketmessage',
            table='campus_ticketmessage',
        ),
    ]
